### ISSUE TITLE
Logo Design Proposal 

### ISSUE THREAD

**Issue by munadikiehl** [cyclestreets/ios#116]
Dear Sir/Madam,
Hi, my name is Munadi Kiehl. I'm a graphic designer and I would like to collaborate on your open source project.

After I review your project, your app is very good. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free.
If you're interested in, please, let me know.

Best Regard,
Munadi Kiehl

**Comment by mvl22** [comment]
Thanks for the offer, but we do not have any plans to change our logo.

PS May I suggest that you take the trouble to e-mail each of the many organisations that have been approaching, rather than using the bug system. Repository issues are not really designed for general approaches to an organisation.
